apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-backend
  labels:
    app: bcse
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: road-backend
  template:
    metadata:
      labels:
        app: road-backend
    spec:
      containers:
      - name: road-backend
        image: cloudsihmar/road-backend:latest  
        ports:
        - containerPort: 8080 
---
